<?php
$state = 'California';
$topheadline = 'California top headline.';
$bigtopheadline = 'California big top headline.';
$story1 = 'California story 1.';
$story1link = '#';
$story2 = 'California story 2.';
$story2link = '#';
$story3 = 'California story 3.';
$story3link = '#';
$story4 = 'California story 4.';
$story4link = '#';
$story5 = 'California story 5.';
$story5link = '#';
$story6 = 'California story 6.';
$story6link = '#';
$story7 = 'California story 7.';
$story7link = '#';
$story8 = 'California story 8.';
$story8link = '#';
$story9 = 'California story 9.';
$story9link = '#';
$story10 = 'California story 10.';
$story10link = '#';
$story11 = 'California story 11.';
$story11link = '#';
$story12 = 'California story 12.';
$story12link = '#';
?>