<?php
$state = 'Iowa';
$topheadline = 'Iowa top headline.';
$bigtopheadline = 'Iowa big top headline.';
$story1 = 'Iowa story 1.';
$story1link = '#';
$story2 = 'Iowa story 2.';
$story2link = '#';
$story3 = 'Iowa story 3.';
$story3link = '#';
$story4 = 'Iowa story 4.';
$story4link = '#';
$story5 = 'Iowa story 5.';
$story5link = '#';
$story6 = 'Iowa story 6.';
$story6link = '#';
$story7 = 'Iowa story 7.';
$story7link = '#';
$story8 = 'Iowa story 8.';
$story8link = '#';
$story9 = 'Iowa story 9.';
$story9link = '#';
$story10 = 'Iowa story 10.';
$story10link = '#';
$story11 = 'Iowa story 11.';
$story11link = '#';
$story12 = 'Iowa story 12.';
$story12link = '#';
?>